#!/bin/bash
echo Enter the three numbers
read n1
read n2
read n3
if [ $n1 -gt $n2 ] && [ $n1 -gt $n3 ]
then
echo $n1 is greatest of 3 numbers
elif [ $n2 -gt $n1 ] && [ $n2 -gt $n3 ]
then
echo $n2 is greatest of 3 numbers
else
echo $n3 is greatest of 3 numbers
fi
